version: "3"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "miam"
    ports:
      - "5434:5432"

  frontend:
    build: ./frontend
    container_name: miam_frontend
    expose:
    - 80
    restart: unless-stopped

  backend:
    build: ./backend
    network_mode: bridge
    container_name: miam_backend
    ports:
      - 8086:8080
    restart: unless-stopped