# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MIAM CI'S WORKFLOWS

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: [ master ]

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '/.*' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,fix,task' # All branches should start with the given prefix
          ignore: master # Ignore exactly matching branch names from convention
          min_length: 15 # Min length of the branch name
          max_length: 80 # Max length of the branch name
  build:
    needs: branch-naming-rules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      run: gradle build
